project:
  type: website
  output-dir: docs  # This will create a docs folder

website:
  title: "Bioinformatics Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data_catalogue.qmd
        text: Data Catalogue
      - text: "Analyses"
        menu:
          - href: analysis/gwas_qc.qmd
            text: "GWAS QC"
          - href: analysis/prs_analysis.qmd
            text: "PRS Analysis"
          - href: analysis/analysis_template.qmd
            text: "Analysis template"
  sidebar:
    - title: "Analyses"
      contents:
        - analysis/gwas_qc.html
        - analysis/prs_analysis.html
        - analysis/analysis_template.html
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 2
    code-fold: true
    number-sections: true
    css: styles.css
