project:
  type: website

website:
  title: "Bioinformatics Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_catalogue.qmd
        text: Data Catalogue
      - text: Analysis
        menu:
          - href: gwas.qmd
            text: GWAS QC
          - href: prs.qmd
            text: PRS Calculation
          - href: de_analysis.qmd
            text: Differential Expression
  search: true

format:
  html:
    theme: cosmo
    toc: true
